### ISSUE TITLE
Convert Angular 2 Beta Burndown to Angular 2

### ISSUE THREAD

**Issue by juristr** [juristr/juristr.github.com#5]
As discussed here

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/juristr">@juristr</a> <a href="https://twitter.com/BeyondJava">@BeyondJava</a> tiny bit sounds fun to convert! I say we do it, I mean it is for tracking Angular2 issues ;)</p>&mdash; Nathan Walker (@wwwalkerrun) <a href="https://twitter.com/wwwalkerrun/status/663983845000134656">November 10, 2015</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Let's convert it :smiley:

**Comment by NathanWalker** [comment]
On it :+1:

**Comment by NathanWalker** [comment]
It's the quick and dirty so please feel free to refactor. I can think of several things to improve but that should get us there.

Btw, I removed `node_modules` from `git` and you may need a couple of them committed back to release to your blog so please keep that in mind.

Cheers :+1:

**Comment by NathanWalker** [comment]
Oh and it builds into a `dist` folder which you may want to commit for that to be served.

**Comment by juristr** [comment]
Yep, have seen that. Hope to be able to give it a closer look today after work and then merge it in. I'll put a note somewhere with a link to your Twitter profile :smile: 

I'll let u know
