### ISSUE TITLE
I want to use this theme with plugins for my Blog. Best way to start ?

### ISSUE THREAD

**Issue by ghost** [juristr/juristr.github.com#7]
Hi. I am fascinated by kudos, table of contents and many other similar stuff.  
Can you please write a blog on how to start with minimal support ?

**Comment by juristr** [comment]
Can you add the link of the specific blog post you liked? I'm currently experimenting with different themes here, so I'm not sure which one you meant :smile:

**Comment by ghost** [comment]
I meant http://juristr.com/ as a whole. I observed on some blog posts you have table of contents, on some a cover photo. The complete platform fascinates me.

**Comment by juristr** [comment]
Well, it's handmade CSS I wrote, taking ideas from various other sites. Simply take a look at the CSS. Everything is based on [Jekyll](https://jekyllrb.com/) as you may already know. I also thought about creating a proper Jekyll template project which others could use, similar to what [Zach Holman did](http://zachholman.com/posts/left/).

Regarding the Kudos. They're based on a custom script I wrote with Firebase as the backend. You can read more about that here: [http://juristr.com/blog/2014/12/kudos-for-your-site/](http://juristr.com/blog/2014/12/kudos-for-your-site/)

**Comment by juristr** [comment]
@theideamachine Just some things
- please remove my Analytics tracking code, otherwise I'll get "wrong visits" counted. It's [here](https://github.com/juristr/juristr.github.com/blob/master/_includes/analytics.html)
- learn from my code and then adapt it to your needs. Make it your own, with your own style :wink: 

Enjoy

**Comment by ghost** [comment]
Thanks a lot! :+1:

**Comment by ghost** [comment]
theideamachine.github.io
Built this blog using your repository. But it is slow. Can you help in improving ?
We can launch it in for jekyll themes as well.

**Comment by juristr** [comment]
@theideamachine What do u mean by "slow"?

Btw, could u please put [this article offline](http://theideamachine.github.io/blog/2015/12/componentizing-workflow/) as it is an exact copy of mine? Thx

**Comment by ghost** [comment]
Sorry for putting up your article. I had it there only for testing purposes.
By slow I mean, network intensive.
If I audit the webpage use chrome dev tools, it shows many suggestions.

**Comment by juristr** [comment]
Oh, yep, I know :blush:. Would have to optimize that on my own blog as well. Just don't have the time right now, unfortunately.
